// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHookBin.Database;

namespace WebHookBin.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteLogDatabaseContext))]
    [Migration("20201017144622_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("WebHookBin.Database.Model.Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("Header");
                });

            modelBuilder.Entity("WebHookBin.Database.Model.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("WebHookBin.Database.Model.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("QueryParameter");
                });

            modelBuilder.Entity("WebHookBin.Database.Model.Header", b =>
                {
                    b.HasOne("WebHookBin.Database.Model.LogEntry", null)
                        .WithMany("Headers")
                        .HasForeignKey("LogEntryId");
                });

            modelBuilder.Entity("WebHookBin.Database.Model.QueryParameter", b =>
                {
                    b.HasOne("WebHookBin.Database.Model.LogEntry", null)
                        .WithMany("QueryParameters")
                        .HasForeignKey("LogEntryId");
                });

            modelBuilder.Entity("WebHookBin.Database.Model.LogEntry", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
